### ISSUE TITLE
Gene predictions of organelle genomes in addition to nuclear eukaryotic genome?

### ISSUE THREAD

**Issue by JSSaini** [cjneely10/EukMetaSanity#14]
Hi, I have obtained the protein-coding genes of the nuclear eukaryotic genome. May I know if this tool also works on organelle genomes including mitochondria and chloroplasts of respective eukaryotic genomes? Thank you.

**Comment by cjneely10** [comment]
Hi @JSSaini,

Apologies for the terribly late responses to this email. We have not added functionality for direct mitochondria/chloroplast annotation, but we will consider exploring this idea on the next EukMetaSanity update.
