### ISSUE TITLE
installation issues with conda

### ISSUE THREAD

**Issue by bishopia** [cjneely10/EukMetaSanity#6]
I'm trying to install EMS and having an issue with freezing during conda environment creation. I'm using a clean local install of miniconda3 in my cluster home directory (though using the cluster's anaconda module led to the same issue). 

Do the authors have any recommended conda channel setup(s) for this installation (which channels present and what priority if any, etc.)?

See attached log file, where I get stuck solving environments.... Any help much appreciated.
[ems_install_log.txt](https://github.com/cjneely10/EukMetaSanity/files/6969087/ems_install_log.txt)

**Comment by bjtully** [comment]
Hi @bishopia - how long did allow this installation try and solve the environment? We have seen this step take several hours to complete - though it is not clear why conda takes so long as this step actually only has a small number of packages.

**Comment by bishopia** [comment]
I was definitely not giving it enough time. I switched over to a VNC session, giving it all the time it needed, and the conda environments installed properly. Thanks!

**Comment by bjtully** [comment]
Thanks for the follow-up @bishopia. Glad it worked out! Let us know how the rest of EukMetaSanity treats you!
