### ISSUE TITLE
Installation issue with conda

### ISSUE THREAD

**Issue by JSSaini** [cjneely10/EukMetaSanity#7]
Installation freezes during conda environment creation. Tried to install it twice, first left it overnight and then left it for 12 hours at least but no success in installing the tool.

**Comment by cjneely10** [comment]
Hi @JSSaini, thank you for trying out EukMetaSanity.

There have been a couple reported issues with long installation times, so we are currently brainstorming solutions.

Meanwhile, you can try allotting more time (>16 hours). Additionally, a clean conda installation can also decrease EukMetaSanity install times (~8 hours on my system)

Sorry for the inconvenience,
- Chris

**Comment by akrinos** [comment]
If I could provide input - we've been having the same problems recently with `EUKulele` and long installation times. Using `mamba` rather than `conda` appears to resolve the issue. I just attempted to install `EukMetaSanity`'s `conda`-based dependencies with `mamba` and it took under a half an hour, though I recognize this is just one leg of the overall installation process. Maybe you've already tried this!

**Comment by cjneely10** [comment]
@akrinos That is an awesome find, thank you! Let me add in mamba to the installation process and see how it functions.

**Comment by cjneely10** [comment]
The EukMetaSanity installation now proceeds using `mamba` and is far faster!

@JSSaini Please attempt a re-install at your convenience. You may wish to remove existing conda environments, if any:

```
conda remove -y --name EukMS_run --all
conda remove -y --name EukMS_report --all
conda remove -y --name EukMS_refine --all
```
And then follow the installation steps in the [installation README](https://github.com/cjneely10/EukMetaSanity/blob/main/INSTALLATION.md).

Let me know if you have any further issues installing EukMS,
Chris

**Comment by JSSaini** [comment]
Tried the new installation after removing the old stuff. The new installation still running for at least 9 hours. Mamba installation is integrated into the new installation steps? Thank you.

**Comment by cjneely10** [comment]
@JSSaini Sorry, can you please confirm that you are running that latest version of this repo (your `INSTALL.sh` file should have `conda install mamba -n base -c conda-forge` as line 9 of the file)? 

If so, I'll need to double check why there is still the slow installation issue on outside systems.

If not, please pull the latest version of the repo prior to running the installation.

Thanks,

**Comment by JSSaini** [comment]
It worked after getting the updated repo from git. Took less than an hour for the whole installations. Many thanks.

**Comment by JSSaini** [comment]
I see that it starts with the config file but how to create it? "cp $EukMS_run/run-config.yaml ./" is not prepared by default.
