### ISSUE TITLE
errors with test data run

### ISSUE THREAD

**Issue by bishopia** [cjneely10/EukMetaSanity#8]
I'm having trouble getting the test data to run properly.  Maybe it is a problem with which python version is being used/accessed in the pipeline? Any thoughts?

[EMS_test_run.log](https://github.com/cjneely10/EukMetaSanity/files/7014398/EMS_test_run.log)

**Comment by cjneely10** [comment]
Hi @bishopia 

When you attempted this run, did it crash very quickly, or did it take a few hours before it crashed?

If you run `squeue -u <user-id-from-eukms-config-file>` (this userid should be the userid that you use on your system), do you see EukMetaSanity jobs still pending? If so, would you mind sending me a screenshot?

Also, could I potentially see the contents of the directory `/gpfs/data/epscor/ibishop/software/EMS/trials/try1/out/wdir/NAO-all-DCM-20-180-00_bin-2/MetaEukEV.MetaEuk` please?

Thank you for this info,
Chris

**Comment by bishopia** [comment]
It crashed immediately, and was due to incorrect user-id. Once fixed the test run ran smoothly with no errors. Thank you for you help and time.
